name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: texlive-ondemand

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    
    - name: Log in to registry
      # This is where you will update the PAT to GITHUB_TOKEN
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      
    - name: Generate Image Tag
      run: |
        export IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$(date +%s)
        export IMAGE_TAG=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        echo "IMAGE_TAG=$IMAGE_TAG"
        echo "image_tag=$IMAGE_TAG" >> $GITHUB_ENV
        echo "image_tag=$IMAGE_TAG"
        echo "action_state=yellow" >> $GITHUB_ENV
        echo "action_state=yellow"
        
    - name: Test ENV
      run: |
        echo IMAGE_TAG=$IMAGE_TAG
        echo env.IMAGE_TAG=${{env.IMAGE_TAG}}
        echo image_tag=$image_tag
        echo env.image_tag=${{env.image_tag}}
        echo "${{ env.action_state }}"
        echo "env.action_state=${{ env.action_state }}"
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_TAG

    - name: Push image
      run: docker push $IMAGE_TAG
